#!/bin/bash

if ! command -v curl >/dev/null 2>&1; then
    sudo apt install -y curl
fi

# Optional: Include logic to check for proxy availability
RESPONSE=$(curl -I -s --connect-timeout 10 -o /dev/null -w "%{http_code}" "http://10.17.89.69:5000/download/llvm-project-main.zip")
if [ "$RESPONSE" -eq 200 ]; then
    if [ ! -e $HOME/.config/apt-proxy/apt-proxy.pem ]; then
        mkdir -p $HOME/.config/apt-proxy
        wget -P $HOME/.config/apt-proxy http://10.17.89.69:5000/download/apt-proxy.pem
        sudo chown $USER:$USER $HOME/.config/apt-proxy/apt-proxy.pem
    fi
    sudo /usr/bin/apt -o Acquire::http::Proxy="http://10.17.89.69:3142/" \
        -o Acquire::https::Proxy="http://10.17.89.69:3142/" \
        -o Acquire::https::http://10.17.89.69:3142/::CaInfo="$HOME/.config/apt-proxy/apt-proxy.pem" \
        "$@"
else
    sudo /usr/bin/apt "$@"
fi